name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stwartbot-dev" #Must be unique in Heroku
          heroku_email: "marcosoquintanilha@gmail.com"
          env_file: ".env"
        # env:
        #   HD_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
        #   HD_RANDOM_DATA: "Hello"